name: Build OpenWrt x86-64

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: UTC

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    if: github.event.repository.fork == false || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Free disk space
        uses: jlumbroso/free-disk-space@main

      - name: Install dependencies
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget ccache

      - name: SSH connection to Actions
        uses: mxschmitt/action-tmate@master
        if: inputs.ssh == 'true' && github.event_name == 'workflow_dispatch'
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

      - name: Clone OpenWrt source
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Restore OpenWrt download cache
        uses: actions/cache@main
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('.config') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-openwrt-dl-${{ hashFiles('.config') }}-
            
      - name: Restore Feeds cache
        uses: actions/cache@main
        with:
          path: openwrt/feeds
          key: ${{ runner.os }}-feeds-${{ hashFiles('openwrt/feeds.conf') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-feeds-${{ hashFiles('openwrt/feeds.conf') }}-

      - name: Restore ccache
        uses: actions/cache@main
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('.config') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ hashFiles('.config') }}-

      - name: Restore Toolchain cache
        uses: actions/cache@main
        with:
          path: |
            openwrt/staging_dir/toolchain-*
            openwrt/build_dir/toolchain-*
          key: ${{ runner.os }}-toolchain-${{ hashFiles('.config') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-toolchain-${{ hashFiles('.config') }}-
      
      - name: Restore package cache
        uses: actions/cache@main
        with:
          path: |
            openwrt/staging_dir/target-*
            openwrt/build_dir/target-*
          key: ${{ runner.os }}-package-${{ hashFiles('.config') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-package-${{ hashFiles('.config') }}-

      - name: Update feeds
        run: |
          cd openwrt
          if [ -f "$GITHUB_WORKSPACE/$DIY_P1_SH" ]; then
            bash "$GITHUB_WORKSPACE/$DIY_P1_SH" || { echo "Error: diy-part1.sh failed"; exit 1; }
          else
            echo "Warning: diy-part1.sh not found, skipping"
          fi
          ./scripts/feeds update -a
          if [ -f "$GITHUB_WORKSPACE/$DIY_P2_SH" ]; then
            bash "$GITHUB_WORKSPACE/$DIY_P2_SH" || { echo "Error: diy-part2.sh failed"; exit 1; }
          else
            echo "Warning: diy-part2.sh not found, skipping"
          fi
          ./scripts/feeds install -a

      - name: Load custom configuration
        run: |
          if [ ! -d openwrt ]; then
            echo "Error: openwrt directory not found"
            exit 1
          fi
          cd openwrt
          echo "Checking for .config at $GITHUB_WORKSPACE/$CONFIG_FILE"
          ls -la $GITHUB_WORKSPACE
          if [ -f $GITHUB_WORKSPACE/$CONFIG_FILE ]; then
            mv $GITHUB_WORKSPACE/$CONFIG_FILE .config || { echo "Error: Failed to move .config"; exit 1; }
            echo "Custom .config loaded successfully."
          else
            echo "Error: Custom .config not found at $GITHUB_WORKSPACE/$CONFIG_FILE"
            exit 1
          fi
          make defconfig || { echo "Error: make defconfig failed"; exit 1; }

      - name: Download package source
        run: |
          cd openwrt
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          
      - name: Save OpenWrt download cache
        if: always()
        uses: actions/cache/save@main
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('.config') }}-${{ github.sha }}
          
      - name: Enable ccache
        run: |
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
          export CC="ccache gcc"
          export CXX="ccache g++"
          export PATH="/usr/lib/ccache:$PATH"
          ccache -z

      - name: Build OpenWrt
        if: env.no_changes != 'true'
        run: |
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
          export CC="ccache gcc"
          export CXX="ccache g++"
          export PATH="/usr/lib/ccache:$PATH"
          cd openwrt
          make --assume-old=staging_dir/toolchain-* --assume-old=build_dir/toolchain-* toolchain/install -j$(nproc)
          make --assume-old=staging_dir/target-* --assume-old=build_dir/target-* -j$(nproc)

      - name: ccache stats
        run: |
          export CCACHE_DIR=$GITHUB_WORKSPACE/.ccache
          ccache -s

      - name: Save Feeds cache
        if: always()
        uses: actions/cache/save@main
        with:
          path: openwrt/feeds
          key: ${{ runner.os }}-feeds-${{ hashFiles('openwrt/feeds.conf') }}-${{ github.sha }}

      - name: Save ccache
        if: always()
        uses: actions/cache/save@main
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('.config') }}-${{ github.sha }}
     
      - name: Save Toolchain cache
        if: always()
        uses: actions/cache/save@main
        with:
          path: |
            openwrt/staging_dir/toolchain-*
            openwrt/build_dir/toolchain-*
          key: ${{ runner.os }}-toolchain-${{ hashFiles('.config') }}-${{ github.sha }}

      - name: Save package cache
        if: always()
        uses: actions/cache/save@main
        with:
          path: |
            openwrt/staging_dir/target-*
            openwrt/build_dir/target-*
          key: ${{ runner.os }}-package-${{ hashFiles('.config') }}-${{ github.sha }}

      - name: Organize files
        id: organize
        if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload firmware to artifact
        if: steps.organize.outputs.status == 'success' && !cancelled()
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}
          retention-days: 1

      - name: Generate release tag
        id: tag
        if: env.UPLOAD_RELEASE == 'true' && !cancelled()
        run: |
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          FILE_DATE=$(date +"%Y%m%d")
          FILE_DATE_DOTTED=$(date +"%Y.%m.%d")
          echo "FILE_DATE=$FILE_DATE" >> $GITHUB_ENV
          echo "release_tag=$FILE_DATE_DOTTED-${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "build_date=$BUILD_DATE" >> $GITHUB_OUTPUT
          echo "OpenWrt Build $BUILD_DATE" >> release.txt
          echo "GitHub: ${{ github.repository }}" >> release.txt
          echo "Run: ${{ github.run_number }}" >> release.txt

      - name: Upload firmware to release
        if: steps.organize.outputs.status == 'success' && steps.tag.outputs.release_tag != '' && !cancelled()
        uses: softprops/action-gh-release@master
        with:
          files: |
            ${{ env.FIRMWARE }}/*
            release.txt
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: OpenWrt Build ${{ steps.tag.outputs.release_tag }}
          body: |
            Automated OpenWrt build completed on ${{ steps.tag.outputs.build_date }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}

      - name: Send Telegram notification
        if: success() && !cancelled()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_ID }} \
            -d text="✅ New OpenWrt build #${{ github.run_number }} - ${{ env.FILE_DATE }} released! Check it at https://github.com/${{ github.repository }}/releases/tag/${{ steps.tag.outputs.release_tag }}" || \
            echo "Warning: Failed to send Telegram notification"

      - name: Send Telegram notification on Failure
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_ID }} \
            -d text="❌ OpenWrt build #${{ github.run_number }} failed! Check logs at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" || \
            echo "Warning: Failed to send Telegram notification"

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 5

      - name: Delete old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
